- hosts: bot

  tasks:

    # NOTE copy
    - name: copy .env.production
      copy:
        src: ../.env.production
        dest: ~/app-telegram/.env

    - name: copy go build app-telegram
      copy:
        src: ../app-telegram
        dest: ~/app-telegram/app-telegram

    - name: copy docker-compose.yml
      copy:
        src: ../docker-compose.yml
        dest: ~/app-telegram/docker-compose.yml




    # - name: docker-compose rm
    #   command: docker-compose rm
    #   args:
    #     chdir: ~/app-telegram
    #   register: output

    # - name: docker-compose build
    #   shell: docker-compose build
    #   args:
    #     chdir: ~/app-telegram
    #   register: output

    # - debug: msg={{output.stdout}}

    # NOTE error shell
    # - name: clear intermediate containers
    #   shell: "docker rmi $(docker images -f 'dangling=true' -q)"
    #   args:
    #     chdir: ~/app-telegram
    #   register: output

    # - name: docker-compose up -d
    #   shell: docker-compose up -d
    #   args:
    #     chdir: ~/app-telegram
    #   register: output

    # - debug: msg={{output.stdout}}
