- hosts: bot

  tasks:
    # - name: cat file
    #   command: cat ~/app-telegram/logrus.log
    #   register: file

    # - debug: msg="{{ file.stdout.replace('\\"',':').split('\n') }}"

    - name: docker-compose logs
      command: docker-compose logs app
      args:
        chdir: ~/app-telegram
      register: output

    # - debug: msg="{{ output.stdout }}"
    - debug: msg="{{ output.stdout.replace('\\"',':').split('\n') }}"
